kind: pipeline
name: Kernel Drone

clone:
  depth: 1

steps:
 - name: compile
   image: ubuntu:20.04
   commands:
      - apt-get update -y && apt-get install make gcc bison flex bc libssl-dev -y
      - make android-x86_64_defconfig
      - make -j$(nproc --all)
      - ls arch/x86_64
